BATCH_SIZE: 4
SAVE_ITERATION: 500
NUM_LABELS: 6 # (background, electron, muon, photon, pion, proton)
N_INITIAL_FILTERS:  12
NETWORK_DEPTH:  4
BALANCE_LOSS:  False
LOGDIR: './uresnet_five_particle/'
BASE_LEARNING_RATE:  0.0001
TRAINING: True
RESTORE: False
GPU: 0
TRAINING_ITERATIONS: 10000
LABEL_NAMES:  ['background', 'electron', 'muon', 'photon', 'proton', 'pion']
