# network parameters
NUM_LABELS: 6 # (background, electron, muon, photon, pion, proton)
N_INITIAL_FILTERS:  12
NETWORK_DEPTH:  4
RESIDUAL_BLOCKS_PER_LAYER: 2
LABEL_NAMES:  ['background', 'electron', 'muon', 'photon', 'proton', 'pion']

# training parameters:
BATCH_SIZE: 4
SAVE_ITERATION: 500
BALANCE_LOSS:  True
BASE_LEARNING_RATE:  0.0001
TRAINING: True
TRAINING_ITERATIONS: 1

# General parameters:
LOGDIR: './uresnet_five_particle/'
RESTORE: False

GPU: 0
