BATCH_SIZE: 4
NUM_LABELS: 6 # (background, electron, muon, photon, pion, proton)
N_INITIAL_FILTERS:  16
NETWORK_DEPTH:  4
BALANCE_LOSS:  True
LOGDIR: './uresnet_five_particle/'
BASE_LEARNING_RATE:  0.001
TRAINING: True
RESTORE: False
GPU: 0
TRAINING_ITERATIONS: 20000
LABEL_NAMES:  ['background', 'electron', 'muon', 'photon', 'proton', 'pion']
